version: '3.8'

services:
  planka:
    image: docker.io/meltyshev/planka:latest
    container_name: planka
    hostname: planka
    ports:
      - "${PLANKA_PORT:-8080}:8080"
    volumes:
      - planka_data:/data
    restart: unless-stopped

volumes:
  planka_data:
    name: planka_data
