version: '3.8'

services:
  tine:
    image: docker.io/tinegroupware/tine:latest
    container_name: tine
    hostname: tine
    ports:
      - "${TINE_PORT:-8080}:8080"
    volumes:
      - tine_data:/data
    restart: unless-stopped

volumes:
  tine_data:
    name: tine_data
