version: '3.8'

services:
  virtualtabletop:
    image: docker.io/arnoldsmith86/virtualtabletop:latest
    container_name: virtualtabletop
    hostname: virtualtabletop
    ports:
      - "${VIRTUALTABLETOP_PORT:-8080}:8080"
    volumes:
      - virtualtabletop_data:/data
    restart: unless-stopped

volumes:
  virtualtabletop_data:
    name: virtualtabletop_data
