version: '3.8'

services:
  holesail-switchboard:
    image: docker.io/orenz0/holesail-switchboard:latest
    container_name: holesail-switchboard
    hostname: holesail-switchboard
    ports:
      - "${HOLESAIL_SWITCHBOARD_PORT:-8080}:8080"
    volumes:
      - holesail-switchboard_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  holesail-switchboard_data:
    name: holesail-switchboard_data
