version: '3.8'

services:
  wanderer:
    image: docker.io/herusetiawan1/wanderer:latest
    container_name: wanderer
    hostname: wanderer
    ports:
      - "${WANDERER_PORT:-8080}:8080"
    volumes:
      - wanderer_data:/data
    restart: unless-stopped

volumes:
  wanderer_data:
    name: wanderer_data
