version: '3.8'

services:
  vault:
    image: docker.io/hashicorp/vault:latest
    container_name: vault
    hostname: vault
    ports:
      - "${VAULT_PORT:-8200}:8200"
    restart: unless-stopped
    volumes:
      - vault_data:/data

volumes:
  vault_data:
    name: vault_data
