version: '3.8'

services:
  2fauth:
    image: docker.io/2fauth/2fauth:latest
    container_name: 2fauth
    hostname: 2fauth
    ports:
      - "${2FAUTH_PORT:-8080}:8080"
    volumes:
      - 2fauth_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  2fauth_data:
    name: 2fauth_data
