version: '3.8'

services:
  stremio:
    image: docker.io/n0bodysec/stremio:latest
    container_name: stremio
    hostname: stremio
    ports:
      - "${STREMIO_PORT:-8080}:8080"
    volumes:
      - stremio_data:/data
    restart: unless-stopped

volumes:
  stremio_data:
    name: stremio_data
