version: '3.8'

services:
  pytition:
    image: docker.io/ethibox/pytition:latest
    container_name: pytition
    hostname: pytition
    ports:
      - "${PYTITION_PORT:-8080}:8080"
    volumes:
      - pytition_data:/data
    restart: unless-stopped

volumes:
  pytition_data:
    name: pytition_data
