version: '3.8'

services:
  helipad:
    image: ghcr.io/ericpp/helipad:latest
    container_name: helipad
    hostname: helipad
    ports:
      - "${HELIPAD_PORT:-8080}:8080"
    volumes:
      - helipad_data:/data
    restart: unless-stopped

volumes:
  helipad_data:
    name: helipad_data
