version: '3.8'

services:
  libremdb:
    image: docker.io/thehelpfulidiot/libremdb:latest
    container_name: libremdb
    hostname: libremdb
    ports:
      - "${LIBREMDB_PORT:-8080}:8080"
    volumes:
      - libremdb_data:/data
    restart: unless-stopped

volumes:
  libremdb_data:
    name: libremdb_data
