version: '3.8'

services:
  commet:
    image: docker.io/cmonjeau/commet:latest
    container_name: commet
    hostname: commet
    ports:
      - "${COMMET_PORT:-8080}:8080"
    volumes:
      - commet_data:/data
    restart: unless-stopped

volumes:
  commet_data:
    name: commet_data
