version: '3.8'

services:
  crewai:
    image: docker.io/sageil/crewai:latest
    container_name: crewai
    hostname: crewai
    ports:
      - "${CREWAI_PORT:-8080}:8080"
    restart: unless-stopped
    volumes:
      - crewai_data:/data

volumes:
  crewai_data:
    name: crewai_data
