version: '3.8'

services:
  transmission-openvpn:
    image: docker.io/haugene/transmission-openvpn:latest
    container_name: transmission-openvpn
    hostname: transmission-openvpn
    ports:
      - "${TRANSMISSION_OPENVPN_PORT:-9091}:9091"
    volumes:
      - transmission-openvpn_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  transmission-openvpn_data:
    name: transmission-openvpn_data
