version: '3.8'

services:
  duplicati:
    image: docker.io/duplicati/duplicati:latest
    container_name: duplicati
    hostname: duplicati
    ports:
      - "${DUPLICATI_PORT:-8080}:8080"
    volumes:
      - duplicati_data:/data
    restart: unless-stopped

volumes:
  duplicati_data:
    name: duplicati_data
