version: '3.8'

services:
  librephotos:
    image: docker.io/reallibrephotos/librephotos:latest
    container_name: librephotos
    hostname: librephotos
    ports:
      - "${LIBREPHOTOS_PORT:-8080}:8080"
    volumes:
      - librephotos_data:/data
    restart: unless-stopped

volumes:
  librephotos_data:
    name: librephotos_data
