version: '3.8'

services:
  ryot:
    image: ghcr.io/ignisda/ryot:latest
    container_name: ryot
    hostname: ryot
    ports:
      - "${RYOT_PORT:-8080}:8080"
    volumes:
      - ryot_data:/data
    restart: unless-stopped

volumes:
  ryot_data:
    name: ryot_data
