version: '3.8'

services:
  starbase-80:
    image: ghcr.io/notclickable-jordan/starbase-80:latest
    container_name: starbase-80
    hostname: starbase-80
    ports:
      - "${STARBASE_80_PORT:-8080}:8080"
    volumes:
      - starbase-80_data:/data
    restart: unless-stopped

volumes:
  starbase-80_data:
    name: starbase-80_data
