version: '3.8'

services:
  surrealdb:
    image: docker.io/surrealdb/surrealdb:latest
    container_name: surrealdb
    hostname: surrealdb
    ports:
      - "${SURREALDB_PORT:-8080}:8080"
    volumes:
      - surrealdb_data:/data
    restart: unless-stopped

volumes:
  surrealdb_data:
    name: surrealdb_data
