version: '3.8'

services:
  ifm:
    image: docker.io/digitalmobil/ifm:latest
    container_name: ifm
    hostname: ifm
    ports:
      - "${IFM_PORT:-8080}:8080"
    volumes:
      - ifm_data:/data
    restart: unless-stopped

volumes:
  ifm_data:
    name: ifm_data
