version: '3.8'

services:
  atuin:
    image: docker.io/ceramicwhite/atuin:latest
    container_name: atuin
    hostname: atuin
    ports:
      - "${ATUIN_PORT:-8080}:8080"
    volumes:
      - atuin_data:/data
    restart: unless-stopped

volumes:
  atuin_data:
    name: atuin_data
