version: '3.8'

services:
  pretalx:
    image: docker.io/helmuthb/pretalx:latest
    container_name: pretalx
    hostname: pretalx
    ports:
      - "${PRETALX_PORT:-8080}:8080"
    volumes:
      - pretalx_data:/data
    restart: unless-stopped

volumes:
  pretalx_data:
    name: pretalx_data
