version: '3.8'

services:
  duplicacy:
    image: ghcr.io/azinchen/duplicacy:latest
    container_name: duplicacy
    hostname: duplicacy
    ports:
      - "${DUPLICACY_PORT:-8080}:8080"
    volumes:
      - duplicacy_data:/data
    restart: unless-stopped

volumes:
  duplicacy_data:
    name: duplicacy_data
