version: '3.8'

services:
  meshcentral:
    image: docker.io/meshcentral/meshcentral:latest
    container_name: meshcentral
    hostname: meshcentral
    ports:
      - "${MESHCENTRAL_PORT:-8080}:8080"
    volumes:
      - meshcentral_data:/data
    restart: unless-stopped

volumes:
  meshcentral_data:
    name: meshcentral_data
