version: '3.8'

services:
  restreamer:
    image: docker.io/datarhei/restreamer:latest
    container_name: restreamer
    hostname: restreamer
    ports:
      - "${RESTREAMER_PORT:-8080}:8080"
    volumes:
      - restreamer_data:/data
    restart: unless-stopped

volumes:
  restreamer_data:
    name: restreamer_data
