version: '3.8'

services:
  conduit:
    image: docker.io/freedom4iran/conduit:latest
    container_name: conduit
    hostname: conduit
    ports:
      - "${CONDUIT_PORT:-8080}:8080"
    volumes:
      - conduit_data:/data
    restart: unless-stopped

volumes:
  conduit_data:
    name: conduit_data
