version: '3.8'

services:
  youtubedl-material:
    image: ghcr.io/tzahi12345/youtubedl-material:latest
    container_name: youtubedl-material
    hostname: youtubedl-material
    ports:
      - "${YOUTUBEDL_MATERIAL_PORT:-8080}:8080"
    volumes:
      - youtubedl-material_data:/data
    restart: unless-stopped

volumes:
  youtubedl-material_data:
    name: youtubedl-material_data
