version: '3.8'

services:
  metabase:
    image: docker.io/metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    ports:
      - "${METABASE_PORT:-8080}:8080"
    volumes:
      - metabase_data:/data
    restart: unless-stopped

volumes:
  metabase_data:
    name: metabase_data
