version: '3.8'

services:
  wordpress:
    image: docker.io/library/wordpress:latest
    container_name: wordpress
    hostname: wordpress
    ports:
      - "${WORDPRESS_PORT:-8080}:8080"
    volumes:
      - wordpress_data:/data
    restart: unless-stopped

volumes:
  wordpress_data:
    name: wordpress_data
