version: '3.8'

services:
  lutim:
    image: docker.io/xataz/lutim:latest
    container_name: lutim
    hostname: lutim
    ports:
      - "${LUTIM_PORT:-8080}:8080"
    volumes:
      - lutim_data:/data
    restart: unless-stopped

volumes:
  lutim_data:
    name: lutim_data
