version: '3.8'

services:
  wiki-go:
    image: docker.io/leomoonstudios/wiki-go:latest
    container_name: wiki-go
    hostname: wiki-go
    ports:
      - "${WIKI_GO_PORT:-80}:80"
    volumes:
      - wiki-go_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  wiki-go_data:
    name: wiki-go_data
