version: '3.8'

services:
  excalidraw:
    image: docker.io/excalidraw/excalidraw:latest
    container_name: excalidraw
    hostname: excalidraw
    ports:
      - "${EXCALIDRAW_PORT:-80}:80"
    volumes:
      - excalidraw_data:/data
    restart: unless-stopped

volumes:
  excalidraw_data:
    name: excalidraw_data
