version: '3.8'

services:
  gocron:
    image: ghcr.io/flohoss/gocron:latest
    container_name: gocron
    hostname: gocron
    ports:
      - "${GOCRON_PORT:-8080}:8080"
    volumes:
      - gocron_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  gocron_data:
    name: gocron_data
