version: '3.8'

services:
  zoraxy:
    image: docker.io/zoraxydocker/zoraxy:latest
    container_name: zoraxy
    hostname: zoraxy
    ports:
      - "${ZORAXY_PORT:-8080}:8080"
    volumes:
      - zoraxy_data:/data
    restart: unless-stopped

volumes:
  zoraxy_data:
    name: zoraxy_data
