version: '3.8'

services:
  revealjs:
    image: docker.io/nbrown/revealjs:latest
    container_name: revealjs
    hostname: revealjs
    ports:
      - "${REVEALJS_PORT:-8080}:8080"
    volumes:
      - revealjs_data:/data
    restart: unless-stopped

volumes:
  revealjs_data:
    name: revealjs_data
