version: '3.8'

services:
  mollysocket:
    image: ghcr.io/mollysocket/mollysocket:latest
    container_name: mollysocket
    hostname: mollysocket
    ports:
      - "${MOLLYSOCKET_PORT:-8080}:8080"
    volumes:
      - mollysocket_data:/data
    restart: unless-stopped

volumes:
  mollysocket_data:
    name: mollysocket_data
