#!/usr/bin/env python3
"""Harbor FastAPI wrapper — exposes the LLM orchestrator CLI as a REST API.

Harbor is a CLI tool (`harbor up/down`) for managing LLM backends via Docker.
Requires Docker socket access — mount /var/run/docker.sock at runtime.
This is configured in the docker-compose.yml generated by T03.
"""

import os
import subprocess
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(
    title='Harbor LLM',
    version='1.0.0',
    description='Harbor — LLM orchestrator CLI for managing LLM backends via Docker (av/harbor, 2.9k★). Requires Docker socket access.'
)


class HarborCommand(BaseModel):
    command: str  # e.g., 'up', 'down', 'status', 'ls'


@app.get('/health')
async def health():
    docker_available = os.path.exists('/var/run/docker.sock')
    return {
        'status': 'ok',
        'framework': 'Harbor',
        'upstream': 'av/harbor',
        'docker_socket_available': docker_available,
        'warning': 'Docker socket access required for harbor commands' if not docker_available else None
    }


@app.get('/info')
async def info():
    return {
        'name': 'Harbor',
        'description': 'LLM orchestrator CLI — manage LLM backends (Ollama, vLLM, etc.) via Docker',
        'upstream': 'https://github.com/av/harbor',
        'commands': ['harbor up', 'harbor down', 'harbor status', 'harbor ls'],
        'stars': '2.9k+',
        'requires': 'Docker socket (/var/run/docker.sock)',
        'note': 'Mount Docker socket at runtime. See docker-compose.yml.'
    }


@app.post('/harbor/{cmd}')
async def run_harbor_command(cmd: str):
    """Run a harbor CLI command. Allowed: up, down, status, ls."""
    allowed = {'up', 'down', 'status', 'ls', 'ps'}
    if cmd not in allowed:
        raise HTTPException(
            status_code=400,
            detail=f'Command "{cmd}" not allowed. Allowed: {", ".join(sorted(allowed))}'
        )

    if not os.path.exists('/var/run/docker.sock'):
        raise HTTPException(
            status_code=503,
            detail='Docker socket not available — mount /var/run/docker.sock at runtime'
        )

    try:
        result = subprocess.run(
            ['harbor', cmd],
            capture_output=True,
            text=True,
            timeout=120
        )
        if result.returncode != 0:
            raise HTTPException(
                status_code=500,
                detail=f'harbor {cmd} failed: {result.stderr.strip()}'
            )
        return {
            'status': 'success',
            'command': f'harbor {cmd}',
            'output': result.stdout.strip()
        }
    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=504, detail=f'harbor {cmd} timed out after 120s')
    except FileNotFoundError:
        raise HTTPException(status_code=500, detail='harbor CLI not found — is harbor installed?')


if __name__ == '__main__':
    import uvicorn
    port = int(os.environ.get('HARBOR_LLM_PORT', '8000'))

    if not os.path.exists('/var/run/docker.sock'):
        print('WARN: /var/run/docker.sock not available — harbor commands will fail')
        print('Mount Docker socket: -v /var/run/docker.sock:/var/run/docker.sock')

    uvicorn.run(app, host='0.0.0.0', port=port)
