version: '3.8'

services:
  dashdot:
    image: ghcr.io/mauricenino/dashdot:latest
    container_name: dashdot
    hostname: dashdot
    ports:
      - "${DASHDOT_PORT:-8080}:8080"
    volumes:
      - dashdot_data:/data
    restart: unless-stopped

volumes:
  dashdot_data:
    name: dashdot_data
