version: '3.8'

services:
  loki:
    image: docker.io/grafana/loki:latest
    container_name: loki
    hostname: loki
    ports:
      - "${LOKI_PORT:-3000}:3000"
    volumes:
      - loki_data:/data
    restart: unless-stopped

volumes:
  loki_data:
    name: loki_data
