version: '3.8'

services:
  grocy:
    image: ghcr.io/linuxserver/grocy:latest
    container_name: grocy
    hostname: grocy
    ports:
      - "${GROCY_PORT:-80}:80"
    volumes:
      - grocy_data:/data
    restart: unless-stopped

volumes:
  grocy_data:
    name: grocy_data
