version: '3.8'

services:
  tube:
    image: docker.io/prologic/tube:latest
    container_name: tube
    hostname: tube
    ports:
      - "${TUBE_PORT:-8080}:8080"
    volumes:
      - tube_data:/data
    restart: unless-stopped

volumes:
  tube_data:
    name: tube_data
