version: '3.8'

services:
  aurral:
    image: docker.io/gsariev/aurral:latest
    container_name: aurral
    hostname: aurral
    ports:
      - "${AURRAL_PORT:-8080}:8080"
    volumes:
      - aurral_data:/data
    restart: unless-stopped

volumes:
  aurral_data:
    name: aurral_data
