name: Build Onyx

on:
  push:
    paths:
      - 'scripts/dockerfiles/onyx/**'
      - 'templates/onyx/**'
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-custom.yml
    with:
      template-name: onyx
    secrets: inherit
