name: Build NanoBot

on:
  push:
    paths:
      - 'scripts/dockerfiles/nanobot/**'
      - 'templates/nanobot/**'
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-custom.yml
    with:
      template-name: nanobot
    secrets: inherit
