name: Build Harbor-LLM

on:
  push:
    paths:
      - 'scripts/dockerfiles/harbor-llm/**'
      - 'templates/harbor-llm/**'
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-custom.yml
    with:
      template-name: harbor-llm
    secrets: inherit
